### ISSUE TITLE
Crashes on certain devices

### ISSUE THREAD

**Issue by thedumbtechguy** [Rogero0o/MissView#2]
```
Fatal Exception: java.lang.NoSuchMethodError: android.renderscript.ScriptIntrinsicColorMatrix.create
       at com.roger.missview.library.util.ImageBlurrer.<init>(ImageBlurrer.java:40)
       at com.roger.missview.library.BlurRenderer$GLPictureSet.load(BlurRenderer.java:332)
       at com.roger.missview.library.BlurRenderer.setAndConsumeBitmapRegionLoader(BlurRenderer.java:252)
       at com.roger.missview.library.RenderController$1$1.run(RenderController.java:65)
       at com.roger.missview.library.GLTextureView$GLThread.guardedRun(GLTextureView.java:1238)
       at com.roger.missview.library.GLTextureView$GLThread.run(GLTextureView.java:1015)
```

Device is sm_n7502. OS is 4.3.

My app is minSdk 15. I checked and the earliest of that API is 17.

**Comment by Rogero0o** [comment]
Sorry , maybe you should up the API level ?~

**Comment by thedumbtechguy** [comment]
But the the library specifies a lower api level.
You could put a condition to use the newer one on api 17+ and fallback unto something else in a lower api.

Currently, I use a different layout instead.

**Comment by Rogero0o** [comment]
Yeah , i will solve this problem soon . Thanks for your issue.

**Comment by RamiTrabelsi** [comment]
You should change import of RenderScript to android.support.v8.renderscript and now it works with API 14+
